name: twistale
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.0
  - pandas=2.1.0
  - scikit-learn=1.3.0
  - faiss-cpu=1.7.4
  - fsspec=2023.9.1
  - aiohttp=3.8.5
  - altair=5.1.1
  - pydantic=2.3.0
  - attrs=23.1.0
  - click=8.1.7
  - blinker=1.6.2
  - async-timeout=4.0.3
  - pip:
      - langchain==0.0.295
      - PyPDF2==3.0.1
      - transformers==4.33.2
      - sentence-transformers==2.2.2
      - torch==2.0.1
      - huggingface-hub==0.17.2
      - sentencepiece==0.1.99
      - tokenizers==0.13.3
      - streamlit==1.26.0
      - protobuf==4.24.3
      - regex==2023.8.8
      - requests==2.31.0
      - validators==0.22.0
      -12